services:
  - type: web
    name: realesrgan-api
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
