services:
  - type: web
    name: real-esrgan-api
    env: python
    buildCommand: |
      pip install setuptools==65.5.0 wheel==0.38.4
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
